/**
 * Minimal deterministic fixtures for the domain unit tests.
 *
 * These are NOT benchmark or evaluation data. They are hand-written, tiny, and
 * exist only to exercise schema behaviour. Benchmark datasets are generated by
 * `packages/generator` into `bench/`, are seeded, and are governed by
 * `PREREGISTRATION.md §4`–`§6`; nothing here feeds them and nothing here is
 * ever used as a scenario.
 *
 * No value below is claimed to be real Razorpay data. Identifier suffixes are
 * arbitrary strings that satisfy the documented grammar.
 */

const S14 = "AbCdEf1234567z";

export const PAY_ID = `pay_${S14}`;
export const ORDER_ID = `order_${S14}`;
export const RFND_ID = `rfnd_${S14}`;
export const SETL_ID = `setl_${S14}`;
export const ADJ_ID = `adj_${S14}`;
export const DISP_ID = `disp_${S14}`;
export const BNK_ID = "bnk_0000000000001";
export const MLE_ID = "mle_0000000000001";
export const OBS_ID = "obs_0000000000001";
export const HASH = "a".repeat(64);

/** 2026-08-01T00:00:00Z. Fixed so nothing here reads a clock. */
export const T0 = 1_785_888_000;

/**
 * A captured card payment of Rs 21.00, the amount used in the documented
 * Razorpay fee sample (`DATA_MODEL.md §6`).
 */
export const validPayment = () => ({
  id: PAY_ID,
  entity: "payment" as const,
  amount: 2_100,
  currency: "INR" as const,
  status: "captured" as const,
  order_id: ORDER_ID,
  method: "card" as const,
  captured: true,
  amount_refunded: 0,
  created_at: T0,
});

export const validOrder = () => ({
  id: ORDER_ID,
  entity: "order" as const,
  amount: 2_100,
  amount_paid: 2_100,
  amount_due: 0,
  currency: "INR" as const,
  status: "paid" as const,
  attempts: 1,
  created_at: T0,
});

export const validRefund = () => ({
  id: RFND_ID,
  entity: "refund" as const,
  amount: 500,
  currency: "INR" as const,
  payment_id: PAY_ID,
  status: "processed" as const,
  speed_requested: "normal" as const,
  speed_processed: "normal" as const,
  created_at: T0 + 3_600,
});

export const validSettlement = () => ({
  id: SETL_ID,
  entity: "settlement" as const,
  amount: 2_050,
  status: "processed" as const,
  fees: 0,
  tax: 0,
  utr: "1568176960vxp0rj",
  created_at: T0 + 172_800,
});

/**
 * A payment recon line consistent with the documented sample: amount 2100 at
 * 200 bps gives fee_ex_gst 42, 18% GST on 42 is 7.56 -> tax 8, fee 50, and
 * credit = amount - fee = 2050.
 */
export const validReconLine = () => ({
  entity_id: PAY_ID,
  type: "payment" as const,
  debit: 0,
  credit: 2_050,
  amount: 2_100,
  currency: "INR" as const,
  fee: 50,
  tax: 8,
  on_hold: false,
  settled: true,
  created_at: T0,
  settled_at: T0 + 172_800,
  settlement_id: SETL_ID,
  posted_at: T0 + 172_800,
  credit_type: "default" as const,
  payment_id: null,
  settlement_utr: "1568176960vxp0rj",
  order_id: ORDER_ID,
  method: "card",
  card_network: "Visa" as const,
  card_issuer: "HDFC",
  card_type: "credit",
  dispute_id: null,
});

export const validAdjustmentLine = () => ({
  ...validReconLine(),
  entity_id: ADJ_ID,
  type: "adjustment" as const,
  debit: 1_000,
  credit: 0,
  fee: 0,
  tax: 0,
  payment_id: null,
  order_id: null,
});

export const validBankLine = () => ({
  bank_line_id: BNK_ID,
  value_date: T0 + 259_200,
  amount: 2_050,
  direction: "credit" as const,
  running_balance: 1_000_000,
  bank_ref: "1568176960vxp0rj",
});

export const validLedgerEntry = () => ({
  ledger_entry_id: MLE_ID,
  booked_at: T0,
  order_ref: "SO-2026-0001",
  invoice_no: "INV-0001",
  gross_paise: 2_100,
  expected_net_paise: 2_050,
  gl_account: "1100_GATEWAY_RECEIVABLE" as const,
});

export const validAdjustment = () => ({
  id: ADJ_ID,
  amount: 1_000,
  direction: "debit" as const,
  reason: "chargeback_debit" as const,
  created_at: T0,
  related_entity_id: PAY_ID,
});

export const validDispute = () => ({
  id: DISP_ID,
  payment_id: PAY_ID,
  amount: 2_100,
  status: "open" as const,
  created_at: T0,
});

/** Provenance fields shared by every observation. */
export const provenance = () => ({
  obs_id: OBS_ID,
  source_file: "recon-2026-08.jsonl",
  source_line: 1,
  ingest_hash: HASH,
  ingested_at: T0 + 300_000,
});
